default:
    just --list

# defining scripts in package.json

install:
    bun install

dev:
    bun dev

build:
    bun run build

preview:
    bun preview

prepare:
    bun prepare

check:
    bun check

format:
    bun format

lint:
    bun lint
